// <auto-generated />
using System;
using DealtHands.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealtHands.Migrations
{
    [DbContext(typeof(DealtHandsDbv2Context))]
    [Migration("20260326005009_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DealtHands.ModelsV2.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("RoundCard");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FieldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MonthlyAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("CardId")
                        .HasName("PK__Card__55FECDAE04C2E5A4");

                    b.HasIndex(new[] { "CardType" }, "idx_card_cardtype");

                    b.HasIndex(new[] { "RoundType" }, "idx_card_roundtype");

                    b.ToTable("Card", (string)null);
                });

            modelBuilder.Entity("DealtHands.ModelsV2.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GameId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("GameId")
                        .HasName("PK__Game__2AB897FDEF6AACC0");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("DealtHands.ModelsV2.GameRound", b =>
                {
                    b.Property<long>("GameRoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GameRoundId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime");

                    b.Property<long>("GameSessionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime");

                    b.Property<byte>("RoundNumber")
                        .HasColumnType("tinyint");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("NotStarted");

                    b.HasKey("GameRoundId")
                        .HasName("PK__GameRoun__003F8F05D8CB7DE5");

                    b.HasIndex(new[] { "GameSessionId" }, "idx_gameround_session");

                    b.HasIndex(new[] { "GameSessionId", "RoundNumber" }, "uq_gameround_session_roundnum")
                        .IsUnique();

                    b.ToTable("GameRound", (string)null);
                });

            modelBuilder.Entity("DealtHands.ModelsV2.GameSession", b =>
                {
                    b.Property<long>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GameSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<byte>("CurrentRoundNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Difficulty")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("HostUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Waiting");

                    b.HasKey("GameSessionId")
                        .HasName("PK__GameSess__E588370D2F5B90D0");

                    b.HasIndex(new[] { "JoinCode" }, "UQ__GameSess__FF7C6BA0FE398DA1")
                        .IsUnique();

                    b.HasIndex(new[] { "GameId" }, "idx_gamesession_game");

                    b.HasIndex(new[] { "HostUserId" }, "idx_gamesession_host");

                    b.HasIndex(new[] { "Status" }, "idx_gamesession_status");

                    b.ToTable("GameSession", (string)null);
                });

            modelBuilder.Entity("DealtHands.ModelsV2.Ugc", b =>
                {
                    b.Property<long>("Ugcid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UGCId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Ugcid"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<long>("GameRoundId")
                        .HasColumnType("bigint");

                    b.Property<long>("GameSessionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("RunningTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("SubmittedAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Ugcid")
                        .HasName("PK__UGC__DC0AF6F268FF4BFD");

                    b.HasIndex(new[] { "CardId" }, "idx_ugc_card");

                    b.HasIndex(new[] { "GameRoundId" }, "idx_ugc_round");

                    b.HasIndex(new[] { "GameSessionId" }, "idx_ugc_session");

                    b.HasIndex(new[] { "UserId" }, "idx_ugc_user");

                    b.HasIndex(new[] { "UserId", "GameRoundId", "CardId" }, "uq_ugc_user_round_card")
                        .IsUnique();

                    b.ToTable("UGC", (string)null);
                });

            modelBuilder.Entity("DealtHands.ModelsV2.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEducator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C7489493E");

                    b.HasIndex(new[] { "Username" }, "UQ__User__536C85E469253162")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105341A37EEF6")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DealtHands.ModelsV2.GameRound", b =>
                {
                    b.HasOne("DealtHands.ModelsV2.GameSession", "GameSession")
                        .WithMany("GameRounds")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gameround_session");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("DealtHands.ModelsV2.GameSession", b =>
                {
                    b.HasOne("DealtHands.ModelsV2.Game", "Game")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("fk_gamesession_game");

                    b.HasOne("DealtHands.ModelsV2.User", "HostUser")
                        .WithMany("GameSessions")
                        .HasForeignKey("HostUserId")
                        .IsRequired()
                        .HasConstraintName("fk_gamesession_host");

                    b.Navigation("Game");

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("DealtHands.ModelsV2.Ugc", b =>
                {
                    b.HasOne("DealtHands.ModelsV2.Card", "Card")
                        .WithMany("Ugcs")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("fk_ugc_card");

                    b.HasOne("DealtHands.ModelsV2.GameRound", "GameRound")
                        .WithMany("Ugcs")
                        .HasForeignKey("GameRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ugc_round");

                    b.HasOne("DealtHands.ModelsV2.GameSession", "GameSession")
                        .WithMany("Ugcs")
                        .HasForeignKey("GameSessionId")
                        .IsRequired()
                        .HasConstraintName("fk_ugc_session");

                    b.HasOne("DealtHands.ModelsV2.User", "User")
                        .WithMany("Ugcs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_ugc_user");

                    b.Navigation("Card");

                    b.Navigation("GameRound");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DealtHands.ModelsV2.Card", b =>
                {
                    b.Navigation("Ugcs");
                });

            modelBuilder.Entity("DealtHands.ModelsV2.Game", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("DealtHands.ModelsV2.GameRound", b =>
                {
                    b.Navigation("Ugcs");
                });

            modelBuilder.Entity("DealtHands.ModelsV2.GameSession", b =>
                {
                    b.Navigation("GameRounds");

                    b.Navigation("Ugcs");
                });

            modelBuilder.Entity("DealtHands.ModelsV2.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Ugcs");
                });
#pragma warning restore 612, 618
        }
    }
}
